package br.usp.ime.escience.expressmatch.model;

// Generated Apr 19, 2014 4:54:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShapeDescriptorType generated by hbm2java
 */
@Entity
@Table(name = "shape_descriptor_type", catalog = "expressMatch")
public class ShapeDescriptorType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String purpose;
	private Date insertDate;
	private ShapeDescriptor shapeDescriptor;

	public ShapeDescriptorType() {
	}

	public ShapeDescriptorType(String name, Date insertDate) {
		this.name = name;
		this.insertDate = insertDate;
	}

	public ShapeDescriptorType(String name, String purpose, Date insertDate,
			ShapeDescriptor shapeDescriptor) {
		this.name = name;
		this.purpose = purpose;
		this.insertDate = insertDate;
		this.shapeDescriptor = shapeDescriptor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "purpose", length = 512)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_date", nullable = false, length = 19)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "shapeDescriptorType")
	public ShapeDescriptor getShapeDescriptor() {
		return this.shapeDescriptor;
	}

	public void setShapeDescriptor(ShapeDescriptor shapeDescriptor) {
		this.shapeDescriptor = shapeDescriptor;
	}

}
