package br.usp.ime.escience.expressmatch.model;

// Generated Apr 19, 2014 4:54:13 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShapeDescriptor generated by hbm2java
 */
@Entity
@Table(name = "shape_descriptor", catalog = "expressMatch")
public class ShapeDescriptor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Symbol symbol;
	private ShapeDescriptorType shapeDescriptorType;
	private Expression expression;
	private String values;
	private Integer lenght;
	private Integer type;
	private Date insertDate;

	public ShapeDescriptor() {
	}

	public ShapeDescriptor(ShapeDescriptorType shapeDescriptorType,
			String values, Integer lenght, Integer type, Date insertDate) {
		this.shapeDescriptorType = shapeDescriptorType;
		this.values = values;
		this.lenght = lenght;
		this.type = type;
		this.insertDate = insertDate;
	}

	public ShapeDescriptor(Symbol symbol,
			ShapeDescriptorType shapeDescriptorType, Expression expression,
			String values, Integer lenght, Integer type, Date insertDate) {
		this.symbol = symbol;
		this.shapeDescriptorType = shapeDescriptorType;
		this.expression = expression;
		this.values = values;
		this.lenght = lenght;
		this.type = type;
		this.insertDate = insertDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "symbol_id")
	public Symbol getSymbol() {
		return this.symbol;
	}

	public void setSymbol(Symbol symbol) {
		this.symbol = symbol;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ShapeDescriptorType getShapeDescriptorType() {
		return this.shapeDescriptorType;
	}

	public void setShapeDescriptorType(ShapeDescriptorType shapeDescriptorType) {
		this.shapeDescriptorType = shapeDescriptorType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expression_id")
	public Expression getExpression() {
		return this.expression;
	}

	public void setExpression(Expression expression) {
		this.expression = expression;
	}

	@Column(name = "values", nullable = false, length = 2048)
	public String getValues() {
		return this.values;
	}

	public void setValues(String values) {
		this.values = values;
	}

	@Column(name = "lenght", nullable = false)
	public Integer getLenght() {
		return this.lenght;
	}

	public void setLenght(Integer lenght) {
		this.lenght = lenght;
	}

	@Column(name = "type", nullable = false)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_date", nullable = false, length = 19)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

}
